{{-- 
This is a minimal placeholder view for Postmark template emails.
The actual email content is generated by Postmark using the template API.
--}}
<html>
<body>
    <p>This email is sent via Postmark template API.</p>
</body>
</html>