<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Invitation>
 */
class InvitationFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'organization_id' => \App\Models\Organization::factory(),
            'email' => $this->faker->unique()->safeEmail(),
            'invited_by' => \App\Models\User::factory(),
            'role' => $this->faker->randomElement(['owner', 'editor', 'reviewer', 'viewer']),
            'status' => 'pending',
            // Token and expires_at are auto-generated by the model boot method
        ];
    }
}
